@startuml Fabric Digital Commerce Platform Overview
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-1/dist

!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Web/AzureCDN.puml
!includeurl AzurePuml/Analytics/all.puml

!includeurl AzurePuml/Storage/AzureStorSimple.puml
!includeurl AzurePuml/Databases/AzureCosmosDb.puml
!includeurl AzurePuml/Databases/AzureDatabaseForPostgreSQL.puml
!includeurl AzurePuml/Analytics/AzureEventHub.puml
!includeurl AzurePuml/Integration/AzureServiceBus.puml
!includeurl AzurePuml/Storage/AzureBlobStorage.puml
!includeurl AzurePuml/Integration/AzureEventGrid.puml


!include DEVICONS/java.puml
!include DEVICONS/mongodb.puml
!include DEVICONS/dotnet.puml
!include DEVICONS/angular.puml

!include DEVICONS2/docker.puml

!include FONTAWESOME/users.puml
!include FONTAWESOME/cubes.puml

skinparam wrapWidth 200

' LAYOUT_AS_SKETCH()
UpdateSkinparamsAndLegendEntry("external_system", $bgColor=Red, $fontColor=White, $borderColor=Black)


LAYOUT_LEFT_RIGHT()
' LAYOUT_TOP_DOWN()

' People
Person(system_user, "System Integrators", "Connect different systems within an enterprise", users)
Person(dev_user, "Application Developers", "Build modular and scalable systems", users)
Person(sre_user, "Site Reliability Engineers", "Use message brokers to monitor and manage system health", users)


' Containers
Container_Boundary(fabric_dcp, "Fabric Digital Commerce Platform Kubernetes Workload Cluster"){  
	' Utility
	Container(commander.console, "Commander.Console", "Dotnet C#", "Digital.Commerce.Platform Command Utility", "dotnet")
	' Single instance
	Container(fabric.commander.console, "FabricCommander", "Dotnet C#", "Digital.Commerce.Platform Command Utility", "dotnet")
	Container(search.commander.console, "SearchCommander", "Dotnet C#", "Digital.Commerce.Platform Command Utility", "dotnet")
	Container(inventory.commander.console, "InventoryCommander", "Dotnet C#", "Digital.Commerce.Platform Command Utility", "dotnet")
	Container(teamdiscount.commander.console, "TeamDiscountCommander", "Dotnet C#", "Digital.Commerce.Platform Command Utility", "dotnet")

	' Microservices
	' Scaleable
	Container(fabric.console, "Fabric.Console", "Dotnet C#", "Digital.Commerce.Platform Microservice", "dotnet")
	Container(search.console, "Search.Console", "Dotnet C#", "Digital.Commerce.Platform Microservice", "dotnet")
	Container(inventory.console, "Inventory.Console", "Dotnet C#", "Digital.Commerce.Platform Microservice", "dotnet")
	Container(clubmembership.console, "ClubMembership.Console", "Dotnet C#", "Digital.Commerce.Platform Microservice", "dotnet")
	Container(teamdiscount.console, "TeamDiscount.Console", "Dotnet C#", "Digital.Commerce.Platform Microservice", "dotnet")
	
	' Storage
	AzureBlobStorage(blob_storage, "Blob Storage", "File Storage For Category, Product and Adobe data")
	AzureEventGrid(event_grid, "Event Grid", "Event Triggers to Service Bus Queue")	
	' Databases
	AzureCosmosDb(cosmos_db, "CosmosDb", "Cosmos NoSQL or MongoDb") 
	' AzureDatabaseForPostgreSQL(cosmos_postgres_db, "CosmosDb", "Mongodb, Postgres and NoSQL") 
	Container(mongo_db_docker, "MongoDb", "Dockerised Local MongoDb", "MongoDb", "docker") 	
	' Message and Stream Brokers
	AzureEventHub(eventhub_cluster, "EventHubs", "Azure Event Hub Cluster or Broker") 
	AzureServiceBus(service_bus, "ServiceBus", "Azure Service Bus") 
	' External System
	System_Ext(fredhopper, "Attraqt or Fredhopper", "Ecommerce Solutions and Search", "cubes")	
	
	' Templating engine
	Container(dcp.template, ".NetCore Templating Engine", "Dotnet C#", "Digital.Commerce.Platform.Templates", "dotnet")
}

' Hybris Systems
System(hybris, "Hybris Azure Platform (Discussion detail only)"){	
	Container(hybris_api, "Hybris API", "Java and SAP SDK", "Hybris API", "java")
	System_Ext(sap_hybris, "SAP Hybris", "Ecommerce platform B2B B2C", "cubes")
	System_Ext(sap_cdc, "SAP CIAM or GIGYA", "SAP customer and identity access management", "cubes")	
	Container(hybris_app, "Current Newlook Website", "Angular", "Newlook.com", "angular")
}

' Rel(hybris_app, commander.console, "Streams XML Inventory stockfeed", "HTTP Response")
Rel(commander.console, fredhopper, "Gateway Connection to API", "HTTP")

' People
Rel(system_user, fabric_dcp, "Uses", "AMQP")
Rel(dev_user, fabric_dcp, "Uses", "AMQP")
Rel(sre_user, fabric_dcp, "Uses", "AMQP")

' Container relationships
Rel(hybris, eventhub_cluster, "Produces", "AMQP")

' File Storage Eventing 
Rel(blob_storage, event_grid, "File upload trigers event", "BlobCreated")
Rel(event_grid, service_bus, "Triggers Queue", "BlobCreatedEvent")

' Commander Console

Rel(commander.console, eventhub_cluster, "Commands", "AMQP")
Rel(commander.console, blob_storage, "Uploads file", "HTTP/HTTPS/SDK")
Rel(sap_hybris, blob_storage, "Uploads file", "HTTP/HTTPS/SDK")

' Fabric (currently Product) Microservice
' Rel(fabric.console, cosmos_postgres_db, "Uses", "Azure Service Bus")
Rel(fabric.console, eventhub_cluster, "Produces Streamed Message", "AMQP")
Rel(fabric.console, search.console, "Produces Events", "AMQP")
Rel(inventory.console, eventhub_cluster, "Produces Streamed Message", "AMQP")
Rel(teamdiscount.console, eventhub_cluster, "Produces Streamed Message", "AMQP")
Rel(inventory.console, search.console, "Produces Events", "AMQP")

Rel(eventhub_cluster, fabric.console, "Consumes Streamed Message", "AMQP")
Rel(eventhub_cluster, inventory.console, "Consumes Streamed Message", "AMQP")
Rel(eventhub_cluster, teamdiscount.console, "Consumes Streamed Message", "AMQP")

Rel(fabric.commander.console, eventhub_cluster, "Produces Streamed Message", "AMQP")
Rel(fabric.commander.console, search.console, "Produces Events", "AMQP")
Rel(inventory.commander.console, eventhub_cluster, "Produces Streamed Message", "AMQP")
Rel(inventory.commander.console, search.console, "Produces Events", "AMQP")

' Search Microservice
Rel(search.console, service_bus, "Produces Messages", "Message Producer")
Rel(fabric.console, service_bus, "Produces Messages", "Message Producer")
Rel(inventory.console, service_bus, "Produces Messages", "Message Producer")
Rel(teamdiscount.console, service_bus, "Produces Messages", "Message Producer")
Rel(service_bus, search.console, "Consumes Messages", "Message Broker")
Rel(service_bus, fabric.console, "Consumes Messages", "Message Broker")
Rel(service_bus, inventory.console, "Consumes Messages", "Message Broker")
Rel(service_bus, teamdiscount.console, "Consumes Messages", "Message Broker")
Rel(service_bus, clubmembership.console, "Consumes Messages", "Message Broker")

' Search Microservice
Rel(search.commander.console, service_bus, "Produces Messages", "Message Producer")
Rel(fabric.commander.console, service_bus, "Produces Messages", "Message Producer")
Rel(teamdiscount.commander.console, service_bus, "Produces Messages", "Message Producer")
Rel(inventory.commander.console, service_bus, "Produces Messages", "Message Producer")
Rel(service_bus, inventory.commander.console, "Consumes Messages", "Message Broker")


Rel(service_bus, cosmos_db, "Uses", "Cosmos Database")
' Rel(service_bus, cosmos_postgres_db, "Uses", "Cosmos Database")
Rel(service_bus, mongo_db_docker, "Uses", "Local Database")

Rel(eventhub_cluster, search.console, "Consumes Streamed Message", "AMQP")
Rel(search.console, eventhub_cluster, "Produces Streamed Message", "AMQP")
Rel(service_bus, fredhopper, "Populates", "Vendor")

' SAP Hybris
Rel(hybris_api, sap_hybris, "Uses", "HTTP Hybris API/SDK")
Rel(hybris_api, sap_cdc, "Uses", "HTTP Hybris API/SDK")
Rel(hybris_app, inventory.console, "Gets online stockfeed", "HTTP Request every 30 minutes")
Rel(teamdiscount.console, hybris_api, "Sets New Look discount options within SAP", "AMQP")
Rel(clubmembership.console, hybris_api, "Sets New Look club membershup options within SAP", "AMQP")

SHOW_DYNAMIC_LEGEND()

@enduml