@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()
' LAYOUT_TOP_DOWN()

title  Container diagram for DIT Datahub and BED Integration

Person(admin, "Administrator", "Administrator")
Person(sysuser, "System ", "System or Automated User")

Container_Boundary(dit_system, "Department of International Trade"){
    Container(datahub_api, "Datahub API", "Python Django", "Exposes Datahub API aswell as Command Pattern Structure for Automation")
    Container(cellery, "Job Schedular", "Python Cellery", "Task oriented cron based job schedular")
    ContainerDb(datahub_db, "datahub db", "Postgres 10", "Durable persistence storage for Datahub")
}

System_Boundary(bed_system, "Business Engagement Database"){
    System_Ext(salesforce, "Salesforce CRM", "Salesforce integrated CRM platform")
}

Rel(admin, datahub_api, "Manual synchronization of data using")
Rel(sysuser, cellery, "Automates syncronization of data using")
Rel(cellery, datahub_api, "Uses", "Python")
Rel(datahub_api, datahub_db, "Reads/Writes", "Postgres")
Rel(datahub_api, salesforce, "Reads and writes interactions", "async, JSON/HTTPS")

@enduml